version: "3"
services:
  game:
    build: .
    container_name: "game"
    working_dir: /opt/app
    volumes:
      - .:/opt/app
    ports:
      - "127.0.0.1:27800:80"
      - "127.0.0.1:27801:9229"
    tty: true
  wasm:
    container_name: "wasm_game"
    image: wasm
    volumes:
      - ./src/wasm:/home/wasm/src
      - ./public:/home/wasm/public
    command: bash
    tty: true
  static_server:
    container_name: "nginx_game"
    image: nginx:alpine
    volumes:
      - ./public:/usr/share/nginx/html
    ports:
      - "127.0.0.1:27804:80"
  # mongo:
  #   container_name: "mongo_game"
  #   image: mongo
  #   volumes:
  #     - ../../store/mongo_game:/data/db
  #   ports:
  #     - "127.0.0.1:27802:27017"
